name: Main

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: Build
        run: pnpm build

      - name: Package
        run: cd dist && zip -r ../tabkeeper-extension-${{ github.ref_name }}.zip * && cd ..

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            tabkeeper-extension-${{ github.ref_name }}.zip
          generate_release_notes: true
          draft: false
          prerelease: false
          make_latest: true
